version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql.railway.internal
      - DB_PORT=3306
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=DoCVAIlWbrQQBnYzAfIZkFGYeEeYJzmW
      - APP_URL=https://cms-influenceur-production.up.railway.app

    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: DoCVAIlWbrQQBnYzAfIZkFGYeEeYJzmW
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: DoCVAIlWbrQQBnYzAfIZkFGYeEeYJzmW
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: